#! Copyright 2022 VMware, Inc.
#! SPDX-License-Identifier: MIT
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace
  annotations:
    kapp.k14s.io/delete-strategy: orphan
    kapp.k14s.io/update-strategy: skip
